apiVersion: v1
kind: Service
metadata:
  name: huckleberry-api-service
  labels:
    name: huckleberry-api-service
spec:
  type: NodePort
  ports:
    - port: 80
      name: huckleberry-api-http
      targetPort: 5000
      protocol: TCP
  selector:
    name: huckleberry-api
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: huckleberry-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: huckleberry-api
    spec:
      volumes:
      - name: dialogflow-credentials-volume
        secret:
          secretName: dialogflow-credentials
          items:
          - key: credentials.json
            path: dialogflow-credentials.json
      containers:
        - name: huckleberry-api
          image: gcr.io/gunio-tools/huckleberry/api:latest
          imagePullPolicy: Always
          volumeMounts:
          - name: dialogflow-credentials-volume
            mountPath: /var/secrets
            readOnly: true
          env:
            - name: AUTH0_AUDIENCE
              value: 'https://huckleberry.gun.io/api'
            - name: AUTH0_DOMAIN
              value: 'gun-io.auth0.com'
            - name: DB_DATABASE
              value: huckleberry-api
            - name: DB_HOST
              value: '10.7.144.3'
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: sql
                  key: DB_PASSWORD
            - name: DB_PORT
              value: '5432'
            - name: DB_USER
              value: postgres
            - name: PORT
              value: '5000'
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/dialogflow-credentials.json
            - name: GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: github
                  key: GITHUB_CLIENT_ID
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: github
                  key: GITHUB_CLIENT_SECRET
            - name: GITHUB_CLIENT_REDIRECT
              value: 'https://huckleberry.gun.io/integrations/github/callback'
            - name: ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: crypto
                  key: ENCRYPTION_KEY
          ports:
            - containerPort: 5000
          readinessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20
