apiVersion: v1
kind: Service
metadata:
  name: huckleberry-api-service
  labels:
    name: huckleberry-api-service
spec:
  type: NodePort
  ports:
    - port: 80
      name: huckleberry-api-http
      targetPort: 5000
      protocol: TCP
  selector:
    name: huckleberry-api
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: huckleberry-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: huckleberry-api
    spec:
      containers:
        - name: huckleberry-api
          image: gcr.io/gunio-tools/huckleberry/api:latest
          imagePullPolicy: Always
          env:
            - name: PORT
              value: '5000'
          ports:
            - containerPort: 5000
          readinessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20
