apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: huckleberry-client-ingress
  annotations:
    # kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.allow-http: "true"
    # ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.global-static-ip-name: "huckleberry-client-ingress"
spec:
  # tls:
  # - secretName: huckleberry-client-tls
  #   hosts:
  #   - huckleberry.gun.io
  backend:
    serviceName: huckleberry-client-service
    servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: huckleberry-client-service
  labels:
    name: huckleberry-client-service
spec:
  type: NodePort
  ports:
    - port: 80
      name: huckleberry-client-http
      targetPort: 5000
      protocol: TCP
  selector:
    name: huckleberry-client
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: huckleberry-client
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: huckleberry-client
    spec:
      containers:
        - name: huckleberry-client
          image: gcr.io/gunio-tools/huckleberry/client:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
