apiVersion: v1
kind: Service
metadata:
  name: huckleberry-client-service
  labels:
    name: huckleberry-client-service
spec:
  type: NodePort
  ports:
    - port: 80
      name: huckleberry-client-http
      targetPort: 5000
      protocol: TCP
  selector:
    name: huckleberry-client
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: huckleberry-client
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: huckleberry-client
    spec:
      containers:
        - name: huckleberry-client
          image: gcr.io/gunio-tools/huckleberry/client:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
